apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-frobarn
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-frobarn
  template:
    metadata:
      labels:
        app: dev-frobarn
    spec:
      containers:
      - name: dev-frobarn
        image: frobarn/webapp:latest
        ports:
        - containerPort: 8000